[profile.default]
src = "src"
out = "out"
libs = ["lib"]

solc_version = "0.8.28"
optimizer = true
optimizer_runs = 200
evm_version = "cancun"


fs_permissions = [{ access = "read", path = "./" }]

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "account-abstraction/=lib/account-abstraction/",
]

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
